thruster_compliance_port_aft:
        pose: '-2.25 1 0 0 0 0'
        size: '1 1 1.2'
        capacity: '1'
thruster_compliance_star_aft:
        pose: '-2.25 -1 0 0 0 0'
        size: '1 1 1.2'
        capacity: '1'
thruster_compliance_port_for:
        pose: '1 1 0 0 0 0'
        size: '1 1 1.2'
        capacity: '1'
thruster_compliance_star_for:
        pose: '1 -1 0 0 0 0'
        size: '1 1 1.2'
        capacity: '1'
thruster_compliance_middle:
        pose: 0.25 0 0 0 0 0
        size: '2.5 1 1.2'
        capacity: '1'
