teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 3
        target: angular.z
        scale: 1.0

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [9]

  turn_left_thruster:
    type: topic
    message_type: std_msgs/Float32
    topic_name: left_thrust_angle
    axis_mappings:
      - axis: 2
        target: data
        scale: -1.0

  turn_right_thruster:
    type: topic
    message_type: std_msgs/Float32
    topic_name: right_thrust_angle
    axis_mappings:
      - axis: 2
        target: data
        scale: -1.0
