sensor_compliance_for:
        pose: '0.8 0 1.8 0 0 0'
        size: '1 1 1'
        capacity: '-1'
sensor_compliance_aft:
        pose: '-0.9 0 1.8 0 0 0'
        size: '0.5 1 1'
        capacity: '-1'
