wamv_camera: 
    num: 3
    allowed_params:
        x
        y
        z
        R
        P
        Y
        name
        post_Y

wamv_gps:
    num: 1
    allowed_params:
        x
        y
        z
        R
        P
        Y
        name
        post_Y

wamv_imu:
    num: 1
    allowed_params:
        x
        y
        z
        R
        P
        Y
        name
        post_Y

lidar:
    num: 2
    allowed_params:
        x
        y
        z
        R
        P
        Y
        name
        post_Y
        type

wamv_p3d:
    num: 0
    allowed_params:
        name
